FROM python:3.13.0a4-alpine

RUN mkdir /app 
WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

COPY main.py /app/

ENTRYPOINT ["python3", "main.py"]